// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPRs6i1wYVINMqfb-qb6DTROA342BHYcQ',
    appId: '1:568495626696:web:6e1a943f015ba06289c8fd',
    messagingSenderId: '568495626696',
    projectId: 'appagendasalao-2b746',
    authDomain: 'appagendasalao-2b746.firebaseapp.com',
    storageBucket: 'appagendasalao-2b746.firebasestorage.app',
    measurementId: 'G-SZPF5N3N76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlwBPoH511HdJ6W3pUX5MMmyW68-AOdKM',
    appId: '1:568495626696:android:4c55733ed3e5dbce89c8fd',
    messagingSenderId: '568495626696',
    projectId: 'appagendasalao-2b746',
    storageBucket: 'appagendasalao-2b746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5rUPRUcKRIvA-eM1XCoid6oGPaz52uC8',
    appId: '1:568495626696:ios:791e589936f1ab1489c8fd',
    messagingSenderId: '568495626696',
    projectId: 'appagendasalao-2b746',
    storageBucket: 'appagendasalao-2b746.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppagendasalao',
  );
}
